/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessSetupSaudiArabiaRouteImport } from './routes/business-setup-saudi-arabia'
import { Route as BusinessSetupJeddahRouteImport } from './routes/business-setup-jeddah'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesVisitVisaRouteImport } from './routes/services_.visit-visa'
import { Route as ServicesVatAccountingRouteImport } from './routes/services_.vat-accounting'
import { Route as ServicesUmrahRouteImport } from './routes/services_.umrah'
import { Route as ServicesStudyVisaRouteImport } from './routes/services_.study-visa'
import { Route as ServicesSaudiKhidmatRouteImport } from './routes/services_.saudi-khidmat'
import { Route as ServicesProServicesRouteImport } from './routes/services_.pro-services'
import { Route as ServicesCrProviderRouteImport } from './routes/services_.cr-provider'
import { Route as ServicesAirlineTicketingRouteImport } from './routes/services_.airline-ticketing'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSetupSaudiArabiaRoute =
  BusinessSetupSaudiArabiaRouteImport.update({
    id: '/business-setup-saudi-arabia',
    path: '/business-setup-saudi-arabia',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessSetupJeddahRoute = BusinessSetupJeddahRouteImport.update({
  id: '/business-setup-jeddah',
  path: '/business-setup-jeddah',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVisitVisaRoute = ServicesVisitVisaRouteImport.update({
  id: '/services_/visit-visa',
  path: '/services/visit-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVatAccountingRoute = ServicesVatAccountingRouteImport.update({
  id: '/services_/vat-accounting',
  path: '/services/vat-accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUmrahRoute = ServicesUmrahRouteImport.update({
  id: '/services_/umrah',
  path: '/services/umrah',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesStudyVisaRoute = ServicesStudyVisaRouteImport.update({
  id: '/services_/study-visa',
  path: '/services/study-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSaudiKhidmatRoute = ServicesSaudiKhidmatRouteImport.update({
  id: '/services_/saudi-khidmat',
  path: '/services/saudi-khidmat',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProServicesRoute = ServicesProServicesRouteImport.update({
  id: '/services_/pro-services',
  path: '/services/pro-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCrProviderRoute = ServicesCrProviderRouteImport.update({
  id: '/services_/cr-provider',
  path: '/services/cr-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAirlineTicketingRoute =
  ServicesAirlineTicketingRouteImport.update({
    id: '/services_/airline-ticketing',
    path: '/services/airline-ticketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/business-setup-jeddah': typeof BusinessSetupJeddahRoute
  '/business-setup-saudi-arabia': typeof BusinessSetupSaudiArabiaRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/airline-ticketing': typeof ServicesAirlineTicketingRoute
  '/services/cr-provider': typeof ServicesCrProviderRoute
  '/services/pro-services': typeof ServicesProServicesRoute
  '/services/saudi-khidmat': typeof ServicesSaudiKhidmatRoute
  '/services/study-visa': typeof ServicesStudyVisaRoute
  '/services/umrah': typeof ServicesUmrahRoute
  '/services/vat-accounting': typeof ServicesVatAccountingRoute
  '/services/visit-visa': typeof ServicesVisitVisaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/business-setup-jeddah': typeof BusinessSetupJeddahRoute
  '/business-setup-saudi-arabia': typeof BusinessSetupSaudiArabiaRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/airline-ticketing': typeof ServicesAirlineTicketingRoute
  '/services/cr-provider': typeof ServicesCrProviderRoute
  '/services/pro-services': typeof ServicesProServicesRoute
  '/services/saudi-khidmat': typeof ServicesSaudiKhidmatRoute
  '/services/study-visa': typeof ServicesStudyVisaRoute
  '/services/umrah': typeof ServicesUmrahRoute
  '/services/vat-accounting': typeof ServicesVatAccountingRoute
  '/services/visit-visa': typeof ServicesVisitVisaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/business-setup-jeddah': typeof BusinessSetupJeddahRoute
  '/business-setup-saudi-arabia': typeof BusinessSetupSaudiArabiaRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services_/airline-ticketing': typeof ServicesAirlineTicketingRoute
  '/services_/cr-provider': typeof ServicesCrProviderRoute
  '/services_/pro-services': typeof ServicesProServicesRoute
  '/services_/saudi-khidmat': typeof ServicesSaudiKhidmatRoute
  '/services_/study-visa': typeof ServicesStudyVisaRoute
  '/services_/umrah': typeof ServicesUmrahRoute
  '/services_/vat-accounting': typeof ServicesVatAccountingRoute
  '/services_/visit-visa': typeof ServicesVisitVisaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/business-setup-jeddah'
    | '/business-setup-saudi-arabia'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/services/airline-ticketing'
    | '/services/cr-provider'
    | '/services/pro-services'
    | '/services/saudi-khidmat'
    | '/services/study-visa'
    | '/services/umrah'
    | '/services/vat-accounting'
    | '/services/visit-visa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/business-setup-jeddah'
    | '/business-setup-saudi-arabia'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/services/airline-ticketing'
    | '/services/cr-provider'
    | '/services/pro-services'
    | '/services/saudi-khidmat'
    | '/services/study-visa'
    | '/services/umrah'
    | '/services/vat-accounting'
    | '/services/visit-visa'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/business-setup-jeddah'
    | '/business-setup-saudi-arabia'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/services_/airline-ticketing'
    | '/services_/cr-provider'
    | '/services_/pro-services'
    | '/services_/saudi-khidmat'
    | '/services_/study-visa'
    | '/services_/umrah'
    | '/services_/vat-accounting'
    | '/services_/visit-visa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  BusinessSetupJeddahRoute: typeof BusinessSetupJeddahRoute
  BusinessSetupSaudiArabiaRoute: typeof BusinessSetupSaudiArabiaRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ServicesAirlineTicketingRoute: typeof ServicesAirlineTicketingRoute
  ServicesCrProviderRoute: typeof ServicesCrProviderRoute
  ServicesProServicesRoute: typeof ServicesProServicesRoute
  ServicesSaudiKhidmatRoute: typeof ServicesSaudiKhidmatRoute
  ServicesStudyVisaRoute: typeof ServicesStudyVisaRoute
  ServicesUmrahRoute: typeof ServicesUmrahRoute
  ServicesVatAccountingRoute: typeof ServicesVatAccountingRoute
  ServicesVisitVisaRoute: typeof ServicesVisitVisaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-setup-saudi-arabia': {
      id: '/business-setup-saudi-arabia'
      path: '/business-setup-saudi-arabia'
      fullPath: '/business-setup-saudi-arabia'
      preLoaderRoute: typeof BusinessSetupSaudiArabiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-setup-jeddah': {
      id: '/business-setup-jeddah'
      path: '/business-setup-jeddah'
      fullPath: '/business-setup-jeddah'
      preLoaderRoute: typeof BusinessSetupJeddahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/visit-visa': {
      id: '/services_/visit-visa'
      path: '/services/visit-visa'
      fullPath: '/services/visit-visa'
      preLoaderRoute: typeof ServicesVisitVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/vat-accounting': {
      id: '/services_/vat-accounting'
      path: '/services/vat-accounting'
      fullPath: '/services/vat-accounting'
      preLoaderRoute: typeof ServicesVatAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/umrah': {
      id: '/services_/umrah'
      path: '/services/umrah'
      fullPath: '/services/umrah'
      preLoaderRoute: typeof ServicesUmrahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/study-visa': {
      id: '/services_/study-visa'
      path: '/services/study-visa'
      fullPath: '/services/study-visa'
      preLoaderRoute: typeof ServicesStudyVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/saudi-khidmat': {
      id: '/services_/saudi-khidmat'
      path: '/services/saudi-khidmat'
      fullPath: '/services/saudi-khidmat'
      preLoaderRoute: typeof ServicesSaudiKhidmatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/pro-services': {
      id: '/services_/pro-services'
      path: '/services/pro-services'
      fullPath: '/services/pro-services'
      preLoaderRoute: typeof ServicesProServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/cr-provider': {
      id: '/services_/cr-provider'
      path: '/services/cr-provider'
      fullPath: '/services/cr-provider'
      preLoaderRoute: typeof ServicesCrProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/airline-ticketing': {
      id: '/services_/airline-ticketing'
      path: '/services/airline-ticketing'
      fullPath: '/services/airline-ticketing'
      preLoaderRoute: typeof ServicesAirlineTicketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  BusinessSetupJeddahRoute: BusinessSetupJeddahRoute,
  BusinessSetupSaudiArabiaRoute: BusinessSetupSaudiArabiaRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ServicesAirlineTicketingRoute: ServicesAirlineTicketingRoute,
  ServicesCrProviderRoute: ServicesCrProviderRoute,
  ServicesProServicesRoute: ServicesProServicesRoute,
  ServicesSaudiKhidmatRoute: ServicesSaudiKhidmatRoute,
  ServicesStudyVisaRoute: ServicesStudyVisaRoute,
  ServicesUmrahRoute: ServicesUmrahRoute,
  ServicesVatAccountingRoute: ServicesVatAccountingRoute,
  ServicesVisitVisaRoute: ServicesVisitVisaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
